### ISSUE TITLE
Uncaught Error: A delayRender was called but not cleared after 25000ms

### ISSUE THREAD

**Issue by ruibaby** [pomber/stargazer#2]
Hi, Pombo

this is awesome project, but i found a little problem.

environment:

```
node -v
v14.15.0

npm -v
6.14.13

ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 12.0.5 (clang-1205.0.22.9)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

params:

```
const defaultProps = {
  repoOrg: "halo-dev",
  repoName: "halo",
  starCount: 19000,
  duration: 180,
};
```

logs:

```
yarn run v1.22.10
$ remotion render src/index.js main out.mp4 --log verbose
Your FFMPEG version: Built from source
📦 (1/3) [=================== ] Bundling code 95%
DevTools listening on ws://127.0.0.1:57747/devtools/browser/53d9fd60-53d6-49b2-af3a-4769f963d21d
[0703/223237.483787:WARNING:address_sorter_posix.cc(388)] FromSockAddr failed on netmask
📦 (1/3) [=================== ] Bundling code 99%[0703/223237.707413:ERROR:command_buffer_proxy_impl.cc(123)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
📦 (1/3) [====================] Bundled code 849ms
Bundled under /var/folders/m9/dgfh8ylj087cjxm_9p3f3r800000gn/T/react-motion-graphics0JNuZO
[0703/223302.979154:INFO:CONSOLE(3318)] "Uncaught Error: A delayRender was called but not cleared after 25000ms. See https://remotion.dev/docs/timeout for help. The delayRender was called:
    at delayRender (http://localhost:3000/bundle.js:3315:32)
    at http://localhost:3000/bundle.js:5689:61
    at Object.Qh [as useState] (http://localhost:3000/bundle.js:401:102)
    at Module.exports.useState (http://localhost:3000/bundle.js:614:281)
    at RemotionVideo (http://localhost:3000/bundle.js:5689:26)
    at Ch (http://localhost:3000/bundle.js:393:137)
    at ck (http://localhost:3000/bundle.js:503:460)
    at bk (http://localhost:3000/bundle.js:486:347)
    at ak (http://localhost:3000/bundle.js:486:278)
    at Tj (http://localhost:3000/bundle.js:486:138)", source: http://localhost:3000/bundle.js (3318)
[Error: Error: A delayRender was called but not cleared after 25000ms. See https://remotion.dev/docs/timeout for help. The delayRender was called:
    at delayRender (http://localhost:3000/bundle.js:3315:32)
    at http://localhost:3000/bundle.js:5689:61
    at Object.Qh [as useState] (http://localhost:3000/bundle.js:401:102)
    at Module.exports.useState (http://localhost:3000/bundle.js:614:281)
    at RemotionVideo (http://localhost:3000/bundle.js:5689:26)
    at Ch (http://localhost:3000/bundle.js:393:137)
    at ck (http://localhost:3000/bundle.js:503:460)
    at bk (http://localhost:3000/bundle.js:486:347)
    at ak (http://localhost:3000/bundle.js:486:278)
    at Tj (http://localhost:3000/bundle.js:486:138)
    at http://localhost:3000/bundle.js:3318:19]
TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (/Users/ryanwang/Workspace/playground/stargazer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
    at DOMWorld.waitForFunction (/Users/ryanwang/Workspace/playground/stargazer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:464:26)
    at Frame.waitForFunction (/Users/ryanwang/Workspace/playground/stargazer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:909:32)
    at Page.waitForFunction (/Users/ryanwang/Workspace/playground/stargazer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:1286:33)
    at Object.getCompositions (/Users/ryanwang/Workspace/playground/stargazer/node_modules/@remotion/renderer/dist/get-compositions.js:50:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.render (/Users/ryanwang/Workspace/playground/stargazer/node_modules/@remotion/cli/dist/render.js:90:19)
    at async cli (/Users/ryanwang/Workspace/playground/stargazer/node_modules/@remotion/cli/dist/index.js:34:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ruibaby** [comment]
When I use these parameters, it works fine.

```
const defaultProps = {
  repoOrg: "halo-dev",
  repoName: "halo",
  starCount: 1800,
  duration: 60,
};
```

https://github.com/ruibaby/stargazer/runs/2977541321?check_suite_focus=true

**Comment by Jaex** [comment]
We also have same problem with these params:

```
> remotion render src/index.js main out.mp4 --log verbose "--props={
  \"duration\": \"15\",
  \"repoName\": \"ShareX\",
  \"repoOrg\": \"ShareX\",
  \"starCount\": \"16000\"
}"
```

https://github.com/ShareX/stargazer/actions/runs/997989322

**Comment by pomber** [comment]
I think that's remotion saying that one of the avatars taking too long to load. 
There may be a way to retry the failed frame soon: https://github.com/remotion-dev/remotion/issues/212

**Comment by yashash1511** [comment]
"duration": "15",
  "repoName": "win11React",
  "repoOrg": "blueedgetechno",
  "starCount": "6300"

with this config too this delayRender error happens

**Comment by Jaex** [comment]
I confirm, it works now for 21k stars: https://github.com/ShareX/stargazer/actions/runs/3139149881

**Comment by adityachallapally** [comment]
I'm still getting this issue:

ff064bcf-14ce-4354-a0a2-d7517a6f395f	ERROR	Error occurred Error: Error: A delayRender() "Rendering <Video /> with src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" at time 0.6666666666666667" was called but not cleared after 28000ms. See https://remotion.dev/docs/timeout for help.
